### PR TITLE
Update PyYAML

### PR DESCRIPTION
**Pull request by normanrz**
There is an incompatibility with `openapi-python-client`, which we are trying to use in one project because of the pyyaml version: https://github.com/openapi-generators/openapi-python-client/blob/main/pyproject.toml#L36

### CODE REVIEW

**Comment by normanrz** [comment]
Hi @TheWall89, sorry to bother you. I was wondering if you had a chance to review my PR. This is currently blocking [our library](https://github.com/scalableminds/webknossos-libs) to upgrade for Python 3.10.

**Comment by TheWall89** [comment]
Hi, thanks for your PR and apologies for the delay (life happens). I just merged https://github.com/TheWall89/inducoapi/pull/5 to fix the GitHub actions and let unit tests run. Can you please merge `master` into your branch so we can re-run the actions? Thanks.

**Comment by normanrz** [comment]
Thanks! I merged `master`. It needs another approval to run the GH actions.

**Comment by TheWall89** [comment]
Mmmh, tests failing on imports. I think I need to properly bump all the dependencies. I'm already doing this in a local branch but I wanted to unblock you with this. Sorry, I'll have another look at this as soon as possible.

**Comment by TheWall89** [comment]
I had half an hour to check this. Please check https://github.com/TheWall89/inducoapi/pull/8 (already merged to master). I'm going to release a new version to PyPI soon.

**Pull request closed without merging**
